[package]
name = "shared"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
yew = "0.21.0"
macros = { path = "../macros" }
uuid = { version = "1.18.1", features = ["v4", "js"] }

